#!/usr/bin/env python3
import base64
import struct
import time
import hashlib
import hmac
import argparse
import re
from cryptography.fernet import Fernet
import getpass

interval = 30
secret_key = ""

parser = argparse.ArgumentParser(description='Leer un archivo y guardar contenido como secret_key')
parser.add_argument('-g', '--archivo', help='nombre del archivo', required=False)
parser.add_argument('-k', '--key', help='generar una nueva contraseña temporal', required=False)
args = parser.parse_args()

if args.archivo:
    with open(args.archivo, 'r') as f:
        contenido = f.read()
    secret_key = contenido
    # Comprobar si el contenido es una cadena de 64 o más caracteres hexadecimales
    hexadecimal_validate=re.compile('^[a-fA-F0-9]{64,}$')
    if hexadecimal_validate.match(contenido):
        with open('ft_otp.key', 'wb') as f:
            # Generar clave de encriptación a partir de la clave secreta
            encryption_key = input("Ingrese la clave de encriptación: ")
            # Convertir la cadena en una secuencia de bytes
            clave_secreta = encryption_key.encode()
            # Calcular el hash SHA-256 de la clave secreta
            hash_clave = hashlib.sha256(clave_secreta).digest()
            # Codificar el hash en base64
            encryption_key = base64.urlsafe_b64encode(hash_clave)
            cipher_suite = Fernet(encryption_key)
            encrypted_content = cipher_suite.encrypt(contenido.encode())
            with open('ft_otp.key', 'wb') as f:
                f.write(encrypted_content)
            print('Contenido encriptado y guardado en ft_otp.key')
    else:
        print('error: key must be 64 hexadecimal characters.')

if args.key:
    tiempo_actual=int(time.time())
    time_slice = int(time.time()) // interval
    time_bytes = struct.pack(">Q", time_slice)

    # Leer el contenido encriptado del archivo
    with open('ft_otp.key', 'rb') as f:
        contenido_encriptado = f.read()
    
    # Generar la clave de encriptación a partir de la clave secreta
    secret_key =  getpass.getpass("Ingrese la clave de encriptación: ")
    encryption_key = base64.urlsafe_b64encode(hashlib.sha256(secret_key.encode()).digest())
    
    # Crear una instancia de Fernet con la clave de encriptación generada
    cipher_suite = Fernet(encryption_key)
    
    # Utilizar el método decrypt de la instancia de Fernet para desencriptar el contenido
    contenido_desencriptado = cipher_suite.decrypt(contenido_encriptado)
    
    # Escribir el contenido desencriptado en un nuevo archivo

    # Convertir el contenido de hex a bytes
    secret_key = contenido_desencriptado
    hmac_sha1 = hmac.new(secret_key, time_bytes, hashlib.sha1).digest()
    offset = hmac_sha1[-1] & 0x0F
    four_bytes = hmac_sha1[offset:offset+4]
    value = struct.unpack(">I", four_bytes)[0]
    totp = value % 1000000
    totp_str = str(totp).zfill(6)

    print(totp_str)
