Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
  end

  config.vm.define "Ubuntu" do |vb|
    vb.vm.hostname = "Ubuntu"
    vb.vm.network "private_network", ip: "192.168.56.200"
    vb.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"

    vb.vm.provider "virtualbox" do |v|
      v.name = ENV["VM_NAME"] || "Ubuntu"
      v.memory = ENV["VM_MEM"] || 2048
      v.cpus = ENV["VM_CPUS"] || 2
    end
  end
end

